apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-config
data:
    default.conf: |
        server {
            listen       80;
            server_name  localhost;
            root   /var/www/html;
            access_log  /var/log/nginx/host_access.log;
            error_log  /var/log/nginx/host_error.log debug;
            location / {
            root   /var/www/html;
            index  index.html index.htm index.php;
            }
            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
            root   /var/www/html;
            }
            location ~ \.php$ {
            root   /var/www/html;
            fastcgi_pass   {phpsvc}:9000;   // php pod service name
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            include        fastcgi_params;
            }
            }
---
apiVersion: v1
kind: Service
metadata:
    name: nginxsvc
spec:
    type: NodePort
    selector:
        app: nginx-server
    ports:
        - protocol: TCP
          port: 8889
          targetPort: 80
          nodePort: 30008
 ---
 apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
  labels:
    name: nginx-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
      - name: nginx-server
        image: nginx:latest
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        - name: webroot
          mountPath: /var/www/html/
        ports:
        - containerPort: 80
      volumes:
      - name: nginx-config
        configMap:
         name: nginx-config
      - name: webroot
        hostPath:
         path: /var/www/html/
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
       kubernetes.io/ingress.class: "nginx"  #此处是重点     
spec:
  rules:
  - host: www.test.com
    http:
      paths:
      - path: /
        pathType: Prefix   #值类型说明参考官方文档，有Exact和Prefix两种
        backend:
          service:
            name: nginxsvc
            port:
              number: 8889
